title: Tongxin Chen
logo: /assets/img/logo.jpg
description: Researcher in Spatio-temporal Data Mining, Urban Mobility and Crime Science at SpacetimeLab, UCL.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
