title: Tongxin Chen
logo: /assets/img/logo.jpg
description: I'm a Lecturer in Spatio-temporal Big Data Analytics, Urban Mobility and Crime Science.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
